#!/usr/bin/expect -f

# 此脚本用于登录某些线上机器
# eg: dssho 127.0.0.1 

# 动态验证码
set code [lindex $argv 0]
set choose [lindex $argv 1]
set machine [lindex $argv 2]

send_user "input params: $code $choose $machine \n"

# 密码
set pass "password"

spawn ssh -p 8088 username@test.com

expect {
    "code:" {
        send "$code\n"
            expect {
                "assword>:" {
                    send "$pass\n"
                }
            }
    }
    "assword>:" {
        send "$pass\n"
    }
}

expect {
    "Option>:" {
        send "$choose\n"
    }
}
interact

# 其它问题
# port 22: Connection refused
# mac上的解决方法: 选择系统偏好设置->选择共享->点击远程登录

# 语法说明
# argc与argv的使用: https://blog.longwin.com.tw/2014/09/bash-shell-scrip-argv-argc-2014/
# send_user: expect时对外界的输出,相当于bash的echo


